// GENERATED by tools/convert.js. Do not edit by hand.
var MYBLOCK_COSMETIC = {"generic":["ins.adsbygoogle","[id^=\"google_ads\"]","[id^=\"div-gpt-ad\"]","iframe[src*=\"doubleclick.net\"]",".ad-banner",".ad-container",".advert","[aria-label=\"Advertisement\"]"],"sites":{"youtube.com":["#masthead-ad","ytd-ad-slot-renderer","ytd-display-ad-renderer"]}};
