// Compiles filter lists into the files the extension actually loads:
//   rules/rules.json   network rules (declarativeNetRequest)
//   cosmetic-data.js   cosmetic selectors for content.js
//
// Usage (from the project folder):
//   node tools/convert.js
//   node tools/convert.js --verbose          list every skipped line
//   node tools/convert.js --full-cosmetic    also include site-specific cosmetic rules from downloaded lists
//
// Inputs: tools/filters.txt (yours) plus any tools/lists/*.txt (see tools/fetch-lists.js).
const fs = require("fs");
const path = require("path");
const ABP = require("../lib/abp.js");

const ROOT = path.join(__dirname, "..");
const MAX_RULES = 30000; // Chrome guarantees this many static rules per extension
const verbose = process.argv.includes("--verbose");
const fullCosmetic = process.argv.includes("--full-cosmetic");

const sources = [{ file: path.join(__dirname, "filters.txt"), siteCosmetic: true }];
const listsDir = path.join(__dirname, "lists");
if (fs.existsSync(listsDir)) {
  for (const f of fs.readdirSync(listsDir).filter((f) => f.endsWith(".txt")).sort()) {
    sources.push({ file: path.join(listsDir, f), siteCosmetic: fullCosmetic });
  }
}

let rules = [];
const seen = new Set();
const generic = new Set();
const sites = {};
const skipped = [];

for (const src of sources) {
  const res = ABP.parse(fs.readFileSync(src.file, "utf8"), { siteCosmetic: src.siteCosmetic });
  for (const r of res.rules) {
    const key = JSON.stringify(r);
    if (!seen.has(key)) { seen.add(key); rules.push(r); }
  }
  res.cosmetic.generic.forEach((s) => generic.add(s));
  for (const [d, list] of Object.entries(res.cosmetic.sites)) {
    sites[d] = [...new Set([...(sites[d] || []), ...list])];
  }
  skipped.push(...res.skipped.map((s) => ({ ...s, file: path.basename(src.file) })));
  console.log(`${path.basename(src.file)}: ${res.rules.length} network rules, ${res.cosmetic.generic.length} generic cosmetic`);
}

if (rules.length > MAX_RULES) {
  console.warn(`Too many rules (${rules.length}). Keeping the ${MAX_RULES} highest-priority ones.`);
  rules.sort((a, b) => b.priority - a.priority); // stable: exceptions and important rules survive
  rules = rules.slice(0, MAX_RULES);
}
rules.forEach((r, i) => { r.id = i + 1; });

const out = "[\n" + rules.map((r) => JSON.stringify(r)).join(",\n") + "\n]\n";
fs.writeFileSync(path.join(ROOT, "rules", "rules.json"), out);

const cosmetic = { generic: [...generic], sites };
fs.writeFileSync(
  path.join(ROOT, "cosmetic-data.js"),
  "// GENERATED by tools/convert.js. Do not edit by hand.\nvar MYBLOCK_COSMETIC = " + JSON.stringify(cosmetic) + ";\n"
);

console.log(`\nWrote ${rules.length} network rules and ${cosmetic.generic.length} generic + ${Object.keys(sites).length} site cosmetic entries.`);

if (skipped.length) {
  const counts = {};
  for (const s of skipped) counts[s.reason] = (counts[s.reason] || 0) + 1;
  console.log(`\nSkipped ${skipped.length} unsupported lines:`);
  Object.entries(counts).sort((a, b) => b[1] - a[1]).slice(0, 12)
    .forEach(([reason, n]) => console.log(`  ${String(n).padStart(6)}  ${reason}`));
  if (verbose) skipped.forEach((s) => console.log(`  [${s.file}] ${s.reason}: ${s.line}`));
  else console.log("  (run with --verbose to see each line)");
}
